### PR TITLE
Autogenerate thumbnail based on metadata input #400 & #399

### PR DESCRIPTION
**Pull request by faizalprbw**
This pull request fix Issue #399 & #400 

Thumbnails will be displayed based on metadata thumbnail input as we can see below:
image

image

If the metadata thumbnail input is unset. It will try to extract images from resource data with WMS format as thumbnail. Here is my WMS instance as data resource:
image

and it will be displayed as thumbnail : 

image

### CODE REVIEW

**Comment by faizalprbw** [comment]
hi @gubuntu what about this :
image
thumbnail div ratio is 1:1

Thumbnail div style needs to be set as `contain` so that whatever the size of wms will always fit to div. 
However, I see another PR related to [thumbnail div style (#422)](https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/pull/422). should I wait until this PR merged or just push the change @Mohab25 ?

**Comment by gubuntu** [comment]
much better

**Comment by Mohab25** [comment]
@faizalprbw please pull first from the development branch and re-push things.

**Comment by faizalprbw** [comment]
@Mohab25 here I have merged with update from development branch

**Pull request merged**
