### PR TITLE
Add setup for datastore extension

### LINKED ISSUE #13: Integrate CKAN datastore extension into dev stack
Lets integrate the [datastore](https://docs.ckan.org/en/2.9/maintaining/datastore.html) extension in order to allow storage of some structure data into the EMC - There is no immediate use case for this, but I'm thinking we can probably use it for the DCPR workflows in some sort

### LINKED ISSUE #14: Integrate data explorer extension into dev stack
The [Data Explorer](https://docs.ckan.org/en/2.9/maintaining/data-viewer.html#data-explorer) extension is described as being very useful for visualizing the contents of the CKAN datastore (which we are integrating in #13. As such lets also integrate it into the EMC

### PR DESCRIPTION
**Pull request by Samweli**
Fixes #13, 
Fixes #14

Adds configurations for setting up ckan datastore extension which in turn enable usage of the data explorer extension.

### CODE REVIEW

**Comment by ricardogsilva** [comment]
I suggest you write an additional ckan command to perform this action - then we can call it as an additional setup step, the same way we currently need to run some additional commands to set up the DB. Look at the `plugin.commands.test.py` module for an example of how to add a ckan command.

Also take into account the following:

https://github.com/ckan/ckan/discussions/6461

**Comment by Samweli** [comment]
> If so, I think you can use sqlalchemy to create a new postgres user and set the correct access controls. Something like:

@ricardogsilva is it ok to prepare the datastore db using the docker commands along with postgres queries instead of ckan commands? eg.
Creating user using
```
docker exec -ti emc-dcpr_datastore-db_1 psql -U datastore-dev -d datastore-dev -c "CREATE USER \"ckan-dev\" WITH PASSWORD 'ckan-dev';"
docker exec -ti emc-dcpr_datastore-db_1 psql -U datastore-dev -d datastore-dev -c "GRANT CONNECT ON DATABASE \"datastore-dev\" TO \"ckan-dev\";"
```

and setting the permission with 

```
docker exec -t emc-dcpr_ckan-web_1 poetry run ckan datastore set-permissions |  docker exec -t emc-dcpr_datastore-db_1 psql -U datastore-dev --set ON_ERROR_STOP=1
```

**Comment by ricardogsilva** [comment]
> is it ok to prepare the datastore db using the docker commands along with postgres queries instead of ckan commands?

What would be the arguments for this?

I would rather do this with set of Python commands so that we have a consistent way to perform all bootstrapping. Additionally, I'd rather perform all bootstrapping against the main CKAN container, not on the DB one.

We can consider doing them as ad-hoc commands on the db conatiner if you have some relevant reason that I'm not thinking of. Please elaborate

**Comment by Samweli** [comment]
> We can consider doing them as ad-hoc commands on the db container if you have some relevant reason that I'm not thinking of. Please elaborate

@ricardogsilva I have updated the PR with the changes you asked for, I couldn't create commands for set permission step as the resulting sql text contains a "\connect" command which is a psql command and can't be used in sqlalchemy execution queries.

I have tried to look for ways to go around the issue but couldn't find a solution, If there is a solution for it then, I ll add the step in the current command, thanks.

**Review by ricardogsilva — COMMENTED** [review]
@Samweli, as discussed offline, I'm taking over this PR.

Thanks for your effort

**Pull request merged**
